spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mywalletdb
    username: mywalletuser
    password: qawsedrf
    driver-class-name: org.postgresql.Driver

#  flyway:
#    user: mywalletuser
#    password: qawsedrf
